version: '3.9'

services:
  touitomamout:
    container_name: "touitomamout"
    build:
      context: ./  # ‚Üê This will build the image from the source code
    restart: unless-stopped
    env_file: ".env"
    environment:
      - ENV_FILE=.env
      - STORAGE_DIR=/data
    volumes:
      - ./data:/data
